on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: ['84.0', 'devedition-84.0b1', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest']
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17' # Specify the Node.js version you need

      - name: Install web-ext
        run: npm install -g web-ext

      - name: Build your add-on (if necessary)
        run: npm install && npm run build # Adjust this line based on how your add-on is built

      - name: Run tests with web-ext
        run: web-ext run --firefox ${{ steps.setup-firefox.outputs.firefox-path }} --source-dir ./dist # Adjust --source-dir to point to your add-on's source directory
