on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: ['84.0', 'devedition-84.0b1', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest']
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17' # Adjust this to your project's Node.js version

      - name: Install dependencies
        run: npm install

      - name: Set Jest Permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Build the project
        run: npm run build # Make sure your package.json has a "build" script

      - name: Run tests
        run: npm test # Make sure your package.json has a "test" script

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Verify Firefox installation
        run: |
          echo Installed Firefox version: ${{ steps.setup-firefox.outputs.firefox-version }}
          ${{ steps.setup-firefox.outputs.firefox-path }} --version
