on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        firefox: ['84.0', 'devedition-84.0b1', 'latest-beta', 'latest-devedition', 'latest-nightly', 'latest-esr', 'latest']
    name: Firefox ${{ matrix.firefox }} sample
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '17' 

      - name: Install dependencies
        run: npm install

      # If your extension needs to be built
      - name: Build addon
        run: npm run build

      - name: Zip and rename bundle.js to bundle.xpi
        run: |
          zip -r bundle.xpi ./dist/bundle.js ./dist/manifest.json
          mv bundle.xpi my_extension.xpi

      - name: Upload Extension Artifact
        uses: actions/upload-artifact@v2
        with:
          name: firefox-extension
          path: my_extension.xpi 

      # - name: Download Extension Artifact
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: firefox-extension
      #     path: my_extension.xpi 

      - name: Set Jest Permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        run: npm test # Make sure your package.json has a "test" script

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: ${{ matrix.firefox }}

      - name: Setup geckodriver
        run: |
          wget https://github.com/mozilla/geckodriver/releases/download/v0.29.0/geckodriver-v0.29.0-linux64.tar.gz
          tar -xzf geckodriver-v0.29.0-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
      
      - name: Run Selenium tests
        run: npm run selenium-test
        env:
           FIREFOX_PATH: ${{ steps.setup-firefox.outputs.firefox-path }}
           XPI_PATH: ${{ github.workspace }}/my_extension.xpi