on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install dependencies
      run: npm ci
    - name: Make Jest executable if found
      run: |
        if [ -f ./node_modules/.bin/jest ]; then
          chmod +x ./node_modules/.bin/jest
          echo "Jest made executable"
        else
          echo "Jest not found"
        fi
    - name: Verify Jest installation
      run: npx jest --version
    - name: List installed binaries
      run: ls -la ./node_modules/.bin/
    - name: Run Jest tests
      run: npm test