on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Generate unique cache key
      id: cache-key
      run: echo "::set-output name=date::$(date +%Y-%m-%d-%H-%M)"
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'package-lock.json'
        cache-key: ${{ steps.cache-key.outputs.date }}-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      run: npm ci
    - name: Make Jest executable if found
      run: |
        if [ -f ./node_modules/.bin/jest ]; then
          chmod +x ./node_modules/.bin/jest
          echo "Jest made executable"
        else
          echo "Jest not found"
        fi
    - name: Verify Jest installation
      run: npx jest --version
    - name: Run Jest tests
      run: npm test
    - name: Cleanup
      if: always()
      run: echo "Cleanup actions if necessary"