name: Node.js CI and SonarCloud Analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: npm ci

    - name: Run tests
      run: npm test

    - name: Print npm debug log if tests fail
      if: failure()
      run: cat /home/runner/.npm/_logs/*.log

    - name: Analyze with SonarCloud
      uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.projectKey=rlmajor_Copy_Base_URL
          -Dsonar.organization=rlmajor
          -Dsonar.sources=.
          -Dsonar.exclusions=tests/**
          # Uncomment and configure these if needed
          # -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
          # -Dsonar.tests=src/test/java
          # -Dsonar.java.binaries=target/classes
        projectBaseDir: .