name: SonarCloud analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  pull-requests: read # allows SonarCloud to decorate PRs with analysis results

jobs:
  Analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
            fetch-depth: 0  # Shallow clones should be disabled
      
      - name: Analyze with SonarCloud
        # You can pin the exact commit or the version.
        # uses: SonarSource/sonarcloud-github-action@v2.2.0
        uses: SonarSource/sonarcloud-github-action@4006f663ecaf1f8093e8e4abb9227f6041f52216
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}   # Ensure this secret is added in GitHub (Settings > Secrets > Actions > New repository secret)
        with:
          # Additional arguments for the SonarScanner CLI
          args: >
            -Dsonar.projectKey=rlmajor_Copy_Base_URL
            -Dsonar.organization=rlmajor
            -Dsonar.sources=.
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            # Uncomment and configure these if needed
            # -Dsonar.tests=src/test/java
            # -Dsonar.java.binaries=target/classes
          projectBaseDir: .
